
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'INTEGER L_BRACE L_BRACKET RESERVED R_BRACE R_BRACKET SEMICOLON STRUCT TYPE_BOOL TYPE_CSTDINT TYPE_PRIMITIVE_FLOAT TYPE_PRIMITIVE_INT TYPE_STRING TYPE_UNSIGNED VAR_NAMEIDL : STRUCT VAR_NAME L_BRACE PARAMS R_BRACE SEMICOLON\n    PARAMS : PARAM\n           | PARAMS PARAM\n    \n    PARAM : TYPE VAR_NAME SEMICOLON\n          | TYPE VAR_NAME ARRAY SEMICOLON\n    \n    TYPE : TYPE_PRIMITIVE_INT\n         | TYPE_PRIMITIVE_FLOAT\n         | TYPE_CSTDINT\n         | TYPE_BOOL\n         | TYPE_STRING\n         | TYPE_UNSIGNED TYPE_PRIMITIVE_INT\n    \n    ARRAY : L_BRACKET INTEGER R_BRACKET\n          | ARRAY L_BRACKET INTEGER R_BRACKET\n    '
    
_lr_action_items = {'STRUCT':([0,],[2,]),'$end':([1,18,],[0,-1,]),'VAR_NAME':([2,7,8,9,10,11,12,17,],[3,16,-6,-7,-8,-9,-10,-11,]),'L_BRACE':([3,],[4,]),'TYPE_PRIMITIVE_INT':([4,5,6,13,15,19,22,],[8,8,-2,17,-3,-4,-5,]),'TYPE_PRIMITIVE_FLOAT':([4,5,6,15,19,22,],[9,9,-2,-3,-4,-5,]),'TYPE_CSTDINT':([4,5,6,15,19,22,],[10,10,-2,-3,-4,-5,]),'TYPE_BOOL':([4,5,6,15,19,22,],[11,11,-2,-3,-4,-5,]),'TYPE_STRING':([4,5,6,15,19,22,],[12,12,-2,-3,-4,-5,]),'TYPE_UNSIGNED':([4,5,6,15,19,22,],[13,13,-2,-3,-4,-5,]),'R_BRACE':([5,6,15,19,22,],[14,-2,-3,-4,-5,]),'SEMICOLON':([14,16,20,26,27,],[18,19,22,-12,-13,]),'L_BRACKET':([16,20,26,27,],[21,23,-12,-13,]),'INTEGER':([21,23,],[24,25,]),'R_BRACKET':([24,25,],[26,27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'IDL':([0,],[1,]),'PARAMS':([4,],[5,]),'PARAM':([4,5,],[6,15,]),'TYPE':([4,5,],[7,7,]),'ARRAY':([16,],[20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> IDL","S'",1,None,None,None),
  ('IDL -> STRUCT VAR_NAME L_BRACE PARAMS R_BRACE SEMICOLON','IDL',6,'p_IDL','yacc.py',6),
  ('PARAMS -> PARAM','PARAMS',1,'p_PARAMS','yacc.py',11),
  ('PARAMS -> PARAMS PARAM','PARAMS',2,'p_PARAMS','yacc.py',12),
  ('PARAM -> TYPE VAR_NAME SEMICOLON','PARAM',3,'p_PARAM','yacc.py',21),
  ('PARAM -> TYPE VAR_NAME ARRAY SEMICOLON','PARAM',4,'p_PARAM','yacc.py',22),
  ('TYPE -> TYPE_PRIMITIVE_INT','TYPE',1,'p_TYPE','yacc.py',34),
  ('TYPE -> TYPE_PRIMITIVE_FLOAT','TYPE',1,'p_TYPE','yacc.py',35),
  ('TYPE -> TYPE_CSTDINT','TYPE',1,'p_TYPE','yacc.py',36),
  ('TYPE -> TYPE_BOOL','TYPE',1,'p_TYPE','yacc.py',37),
  ('TYPE -> TYPE_STRING','TYPE',1,'p_TYPE','yacc.py',38),
  ('TYPE -> TYPE_UNSIGNED TYPE_PRIMITIVE_INT','TYPE',2,'p_TYPE','yacc.py',39),
  ('ARRAY -> L_BRACKET INTEGER R_BRACKET','ARRAY',3,'p_ARRAY','yacc.py',67),
  ('ARRAY -> ARRAY L_BRACKET INTEGER R_BRACKET','ARRAY',4,'p_ARRAY','yacc.py',68),
]
